### PR TITLE
release: unkempt-turtle

### LINKED ISSUE #5509: Users can't connect to dapp or it takes forever
This issue is unresolved
https://github.com/leather-wallet/extension/issues/5021

I see these errors but I am not sure if they are related. It his happening on all dapps. When account data isn't fully loaded yet. It takes forever even when the balance is loaded. This happening especially in wallets with 20 or more accounts and when for example the account balance is still being loaded. I have also seen the same issue (connection to dapp doesn't complete) when balance was just loaded. 

Steps to reproduce
0.  Restore Leather with an existing Secret Key that has 20 or more accounts in it.
1. Click connect on app.alexlab.co
or stacks.gamma.io
or any other dapp
2. Scroll down until you see all the "loading" animations for balance
3. Click one of the accounts with the accounts to connect
4. spinning (to connect) starts and never stops... dapps never connects
image

Possibly unrelated console errors
image

Workarounds
- Wait longer for the balances in the "select account" screen to load (works most of the time)
- Click additional times (sometimes works)

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out Leather build 16d751c — [Extension build](https://github.com/leather-io/extension/actions/runs/9908481493), [Test report](https://leather-io.github.io/playwright-reports/release-unkempt-turtle), [Storybook](https://release-unkempt-turtle--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=release-unkempt-turtle)

This release includes:
- https://github.com/leather-io/issues/issues/98 
- https://github.com/leather-io/extension/issues/4971
- https://github.com/leather-io/extension/issues/5615
- https://github.com/leather-io/extension/issues/4979
- https://github.com/leather-io/extension/issues/5624
- https://github.com/leather-io/extension/issues/5509
- https://github.com/leather-io/extension/issues/4657
- https://github.com/leather-io/extension/issues/5621
- https://github.com/leather-io/extension/issues/4859
- https://github.com/leather-io/extension/issues/4657
- https://github.com/leather-io/mono/pull/259

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]
Tested and lgtm. 🚀

**Comment by 314159265359879** [comment]
Tested 
- Swaps with and without Ledger working again ✅ 
- Throttling, experience is a lot better, especially once initial account data has been loaded on the switch account screen. 😃 
- #4859 / #4657 I see the account number of the active account on Leather. This is not necessarily the account that was signed in with on the dapp but that is related to the dapp not having implemented this https://github.com/leather-io/extension/issues/4859#issuecomment-2208667298 (Luminex and gamma).

Just account number, we used to show relevant (stacks or btc) gas balance too, will we add that again? 
image

Swaps: This is probably out of scope for now but slippage tolerance and swapping fee (and if sponsored or not) should be adjustable. This is covered in the swap or approval redesign because we want to take users through the normal approval UX, right?
image

I will do more tests while I use this PR's build as my daily driver until it is released.

**Comment by fbwoolf** [comment]
Same tests are failing on my branch, fyi.

**Comment by fbwoolf** [comment]
I removed my approval here bc `send-btc.spec` tests are broken.

**Comment by pete-watters** [comment]
> Tested and lgtm. 🚀

Can you please mark it as `Needs work` until we solve the problem with tests? 

I can't do it myself as I opened it and I don't want to just close it

**Review by fbwoolf — CHANGES_REQUESTED** [review]
Blocking until we get tests passing.

**Comment by markmhendrickson** [comment]
> Swaps with and without Ledger working again ✅
> Throttling, experience is a lot better, especially once initial account data has been loaded on the switch account screen. 😃

These are the main things to test, so let's consider this PR as having passed QA.

> Just account number, we used to show relevant (stacks or btc) gas balance too, will we add that again?

Let's address with https://github.com/leather-io/issues/issues/157

> Swaps: This is probably out of scope for now but slippage tolerance and swapping fee (and if sponsored or not) should be adjustable. This is covered in the swap or approval redesign because we want to take users through the normal approval UX, right?

That's correct.

**Review by markmhendrickson — APPROVED** [review]

**Review by fbwoolf — APPROVED** [review]

**Pull request merged**
