### PR TITLE
feat: new onboarding home page redo

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1906850598).

This is a PR to redo the revert of: https://github.com/hirosystems/stacks-wallet-web/pull/2233

cc/ @kyranjamie

### CODE REVIEW

**Comment by fbwoolf** [comment]
@landitus the external link changes have been added here if you want to review...

Screen Shot 2022-02-23 at 6 56 46 PM

**Comment by fbwoolf** [comment]
@landitus the external link changes are ready here...

Screen Shot 2022-02-23 at 7 14 08 PM

Screen Shot 2022-02-23 at 7 16 26 PM

**Comment by fbwoolf** [comment]
Anyone seen where a new design for this empty state is? There must be a new illustration I can swap out here?
cc @eugeniadigon 

Screen Shot 2022-02-23 at 7 46 35 PM

**Comment by ginny-d** [comment]
> Anyone seen where a new design for this empty state is? There must be a new illustration I can swap out here? cc @eugeniadigon
> 
> Screen Shot 2022-02-23 at 7 46 35 PM

Yes, sorry they were on a separate issue: https://github.com/hirosystems/stacks-wallet-web/issues/1809

**Comment by landitus** [comment]
@fbwoolf I've noticed the images of the Empty state are in low-res as well, so we should replace them with 2x versions. Additionally, I'm attaching the new illustration for the No activity state from @eugeniadigon 

Here's how they look:
Home - Balances - Empty State (Small)
Home - Activity - Empty State (Small)


Here are the assets:
[empty-state-illustrations.zip](https://github.com/hirosystems/stacks-wallet-web/files/8134512/empty-state-illustrations.zip)

**Comment by fbwoolf** [comment]
> @fbwoolf I've noticed the images of the Empty state are in low-res as well, so we should replace them with 2x versions. Additionally, I'm attaching the new illustration for the No activity state from @eugeniadigon
> 
I don't feel like these images are current bc `Copy address` is outdated? It now says `Fund your account`?

EDIT: Also feel like the margin b/w the image and text on each is different which seems odd? Why is one 24px but the other 16px?

**Comment by landitus** [comment]
Hi @fbwoolf, apologies for the confusion. These are the latest illustrations indeed. I've mocked the screens more accurately and normalized the spacing here: https://www.figma.com/file/rphxUIsRqG3sLO1rxgJK6T/%F0%9F%8F%A0-Home?node-id=656%3A15585

Screenshot 2022-02-25 at 16 43 34

**Comment by fbwoolf** [comment]
I am having a lot of trouble dropping the extra commits here w/out local build errors. It is slowing me down so I'm going to close this PR and open a new one branched off dev with my commit. New branch is `feat/new-home-page`.

**Pull request closed without merging**
