### PR TITLE
refactor: move test-app specific packages

### LINKED ISSUE #1818: Refactor: `test-app` should be extracted out into new browser app
Currently there are dependencies, that are only used in the `test-app` package, installed in the main wallet's `package.json`.

`test-app` should have its own `package.json` and list its own dependencies. We should remove any test-app packages from the main wallet's package.

### PR DESCRIPTION
**Pull request by beguene**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/1358303829).

Move test-app only packages to devDependencies and remove useless packages from the main app.
I took a different approach than https://github.com/blockstack/stacks-wallet-web/pull/1833
where I move everything to the subfolder but it creates a lots of issues in the building of the test-app.
This way we achieve the same result (removing the useless prod packages).

### CODE REVIEW

**Comment by beguene** [comment]
@fbwoolf @kyranjamie it's ready for review.

**Comment by kyranjamie** [comment]
Have you committed everything? This just moves packages around, right?

An improvement, but I wouldn't say this closes #1818

**Review by kyranjamie — APPROVED** [review]
👍🏼  , but please don't close the issue, as it would be better stiil for testapp to have it's own package json

**Comment by beguene** [comment]
@kyranjamie I explained in the PR description why I took this approach.

**Pull request merged**
