### PR TITLE
fix: add post condition allow warning

### LINKED ISSUE #1152: Improve transaction signing experience for "allow" mode
Not having to pass all post conditions would be useful for devs who want to test, and don't quite care about post conditions just yet. They should be able to sign transactions in 'allow' mode somehow, but for users it should be forced to 'deny' mode. Maybe an advanced toggle somewhere.

image

### PR DESCRIPTION
**Pull request by aulneau**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/1174793972).

This takes a stab at https://github.com/blockstack/stacks-wallet-web/issues/1152

Screen Shot 2021-08-26 at 3 11 44 PM

cc/ @aulneau @kyranjamie @fbwoolf

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]
LGTM!

**Comment by markmhendrickson** [comment]
@jasperjansz please review ASAP so we can ship or make modifications as needed before getting this live.

**Review by beguene — APPROVED** [review]

**Review by kyranjamie — APPROVED** [review]

**Review by jasperjansz — DISMISSED** [review]
2 changes:

- Hide the transfers. Deny mode has conditioned users to see these transfers as guarantees, they are pointless and confusing in the case of allow mode.
- Change the copy

See the design here: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=199%3A4206

**Comment by beguene** [comment]
@jasperjansz What do you mean by 'hide the transfers' ? Do you mean we should hide the full bordered box "The contract will transfer..." ?

**Comment by jasperjansz** [comment]
> @jasperjansz What do you mean by 'hide the transfers' ? Do you mean we should hide the full bordered box "The contract will transfer..." ?

@beguene Yes. In allow mode the transaction can transfer any amount of any token — so the post-conditions displayed are not meaningful and might even mislead users to think that's what's guaranteed to happen.

**Comment by beguene** [comment]
@jasperjansz I made the changes.

allow-mode

@aulneau @fbwoolf Please review my changes.

**Review by aulneau — COMMENTED** [review]
@beguene just one small change around not breaking the [rules of hooks](https://reactjs.org/docs/hooks-rules.html) :)

**Review by fbwoolf — APPROVED** [review]

**Pull request merged**
